### ISSUE TITLE
Function suggestion

### ISSUE THREAD

**Issue by XUJIN-C** [davidaf3/csgo-tracker#2]
Manual end button is required. After the game exits early, the data will overlap with the next one. 😍😍😍

**Comment by davidaf3** [comment]
The current match is stored in memory and, when you close the game before the match ends, the app doesn't get notified about it and the match is kept in memory. So, yeah, an end button is a good addition.

I'm currently preparing my finals, so new feauters won't be added until summer. In the meantime, if you exit the game and the app still shows a match in progress, you can closethe app to clear it from memory. When you open the app again, it will still show a match in progress, but new matches will be recorded properly.

I'm also planning on adding a delete match button. Until that is done, you can remove the match by accessign the database that is stored at `\.csgo-tracker\stats.db` inside your user folder.
